name: movie_revenue
dependencies:
  - python=3
  - nb_conda
  - notebook
  - pip
  - pip:
      - pandas==1.2.4
      - matplotlib==3.4.1
      - scipy==1.6.3
      - seaborn==0.11.1
      - scikit-learn==0.24.2
      - TPOT==0.11.7
      - deap==1.3.1
      - tqdm==4.60.0
      - stopit==1.1.2
      - xgboost==1.4.1
